    name: Evril_Gifts
    main: com.github.Skycrawler67.Evril.Gifts.Gifts
    author: Skycrawler67
    website: http://evril-serveur.servegame.com/
    version: 1.1
    description: >
                 Gift Plugin for EvrilServer.
    load: POSTWORLD
    commands:
      EvrilGift:
        description: Give you a gift!
